/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Player;
import Networking.Networking;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vladimir Vorobyev (vorobvla)
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }
    
    public static  void setup(){
        playerNameLabel.setText(Player.getInstance().getName());
        if (Networking.getInstance().isBroadcast()) {
            noBroadcastLabel.setVisible(false);
            gameInfoPanel.update();
            gameInfoPanel.setupTable();
            new Thread(){
                @Override
                public void run() {
                    while(true){
                        try {
                            Thread.sleep(200);
                            gameInfoPanel.update();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            }.start();
        }else{
            noBroadcastLabel.setVisible(true);
            gameInfoPanel.setVisible(false);
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gameInfoPanel = new GUI.GameInfoPanel();
        AnswerButton = new javax.swing.JButton();
        playerNameLabel = new javax.swing.JLabel();
        noBroadcastLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(420, 250));
        setPreferredSize(new java.awt.Dimension(420, 250));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        setLayout(layout);

        gameInfoPanel.setMinimumSize(new java.awt.Dimension(280, 150));
        gameInfoPanel.setPreferredSize(new java.awt.Dimension(280, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(gameInfoPanel, gridBagConstraints);

        AnswerButton.setText("Answer");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 241;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        add(AnswerButton, gridBagConstraints);

        playerNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        playerNameLabel.setText(Player.getInstance().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(playerNameLabel, gridBagConstraints);

        noBroadcastLabel.setText("No Broadcast from Moderator.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(noBroadcastLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        Player.applyForAnswer();
    }//GEN-LAST:event_AnswerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerButton;
    private static GUI.GameInfoPanel gameInfoPanel;
    private static javax.swing.JLabel noBroadcastLabel;
    private static javax.swing.JLabel playerNameLabel;
    // End of variables declaration//GEN-END:variables
    
}
