/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Networking.Networking;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Vladimir Vorobyev (vorobvla)
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    
    public static MainFrame getInstance() {
        if (instance == null){
            instance = new MainFrame();
        }
        return instance;
    }

    public MainFrame() {
        try {
            setIconImage(ImageIO.read(getClass().getResource("/resources/Icon.png")));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("could not find icon resource");
        }
            initComponents();
            
            setTitle("Player App Prototype");
            showCard("startPanel");
            /*        startPanel.getReadyButton().addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
            readyButtonActionPreformed();
            }           
            });*/
            this.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosing(WindowEvent e) {
                    Networking.getInstance().sendConnTerm();
                    super.windowClosing(e);
                }                
            });
    }
    
    
    public static void showCard(String name){
        //System.out.println(mainPanel.hashCode());
        
       ((CardLayout)mainPanel.getLayout()).show(mainPanel, name);
       //pack();
        
    }
   
 /*   private void readyButtonActionPreformed() {
        System.err.println("showCard(\"gamePanel\")");
        showCard("gamePanel");
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new GUI.StartPanel();
        gamePanel = new GUI.GamePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 250));
        setPreferredSize(new java.awt.Dimension(420, 250));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setLayout(new java.awt.CardLayout());

        /*
        startPanel.setMinimumSize(new java.awt.Dimension(420, 250));
        startPanel.setPreferredSize(new java.awt.Dimension(420, 250));
        mainPanel.add(startPanel, "card2");
        */
        mainPanel.add(startPanel, "startPanel");

        /*
        mainPanel.add(gamePanel, "card3");
        */
        mainPanel.add(gamePanel, "gamePanel");

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.GamePanel gamePanel;
    private static javax.swing.JPanel mainPanel;
    private GUI.StartPanel startPanel;
    // End of variables declaration//GEN-END:variables
    private static MainFrame instance;
    
}
